### PR TITLE
warn if generation prompt does not start with a control code

### PR DESCRIPTION
**Pull request by julien-c**

### CODE REVIEW

**Comment by dimitri320** [comment]
@julien-c great idea, totally get your commit, but how is the control code/token identified right now in the master branch? I don't get how control_codes.txt is being referenced from generate.py right now? Or am I missing something? I'm pretty sure I setup everything right on my V100, but the master branch just doesn't work (runs, but copies the last word over and over, so likely it doesn't see my control code) while the lower_memory branch works just fine. Totally lost to be honest...

**Comment by julien-c** [comment]
Did you try all the different models? Maybe it's an issue with a specific one?

**Comment by julien-c** [comment]
A control code is just a token. So if you start with `Joke A man comes into a bar` "Joke" is just a token like the other ones. Not sure I can help on debugging your specific issue though. Good luck!

**Comment by dimitri320** [comment]
@julien-c thanks a lot, will try running your code, maybe it’ll work. Just strange why my setup doesn’t;to see control code on the master branch.

**Comment by dimitri320** [comment]
@julien-c I’ve got an idea about what might be wrong. I think I might be patching the wrong keras.py file. Can you share the path of this file you are patching (as your setup is GCP with V100, just like mine). Im also using Anaconda Python 3.7 virtual environment setup.

**Comment by keskarnitish** [comment]
Thanks for the PR @julien-c !

@dimitri320 , you should patch wherever `tensorflow_estimator` is. You can find this by 

```
>>> import tensorflow_estimator
>>> tensorflow_estimator.__file__
```

**Pull request merged**
